### PR TITLE
Added open source platforms such as OpenAI gym

### PR DESCRIPTION
**Pull request by nieoh**
Added links to open source platforms. Added a useful blog post series regarding RL using TF.

### CODE REVIEW

**Comment by nieoh** [comment]
I'm interested in helping maintain and curate this repo.

**Comment by hshyunsookim** [comment]
Hi, thanks for the update. Could you also add links to Twitter twrl, facebook's UETorch and TorchCraft, and OpenAI rllab?

**Comment by nieoh** [comment]
Done @hshyunsookim .

**Comment by hshyunsookim** [comment]
Thanks @nieoh !

**Pull request merged**
